import 'dotenv/config'
import { randomUUID } from 'node:crypto'
import { Pool } from 'pg'
import { expect, test, type Page } from '@playwright/test'

const base = 'http://localhost:3000'
const run = randomUUID()
const email = `fase2-${run}@example.com`
const otherEmail = `fase2-other-${run}@example.com`
const password = `Test-${run}!`
const pool = new Pool({ connectionString: process.env.DATABASE_URL })

test.afterAll(async () => {
  // Only delete the fixtures generated by this run; sessions/accounts cascade.
  await pool.query(
    'DELETE FROM addresses WHERE customer_id IN (SELECT id FROM "user" WHERE email = ANY($1))',
    [[email, otherEmail]],
  )
  await pool.query('DELETE FROM "user" WHERE email = ANY($1)', [[email, otherEmail]])
  await pool.end()
})

async function register(page: Page, userEmail: string, name: string) {
  await page.goto(`${base}/registrarse`)
  await page.getByLabel('Nombre completo').fill(name)
  await page.getByLabel('Email', { exact: true }).fill(userEmail)
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(page).toHaveURL(`${base}/cuenta`)
  await expect(page.getByRole('button', { name: 'Menú de mi cuenta' })).toBeVisible()
}

async function addAddress(page: Page, name: string) {
  await page.getByRole('button', { name: 'Agregar dirección' }).click()
  await page.getByLabel('Destinatario').fill(name)
  await page.getByLabel('Teléfono').fill('0981 123456')
  await page.getByLabel('Departamento').selectOption('Central')
  await page.getByLabel('Ciudad').fill('Luque')
  await page.getByLabel('Dirección / referencia').fill('Dirección ficticia de prueba')
  await page.getByLabel('Usar como dirección predeterminada').check()
  await page.getByRole('button', { name: 'Guardar dirección' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
}

test('customer lifecycle, address isolation, default switch and protected routes', async ({
  page,
  browser,
}) => {
  test.setTimeout(180_000)
  expect(await (await page.request.get(`${base}/api/auth/ok`)).json()).toEqual({ ok: true })
  await page.goto(`${base}/cuenta/direcciones`)
  await expect(page).toHaveURL(`${base}/ingresar`)
  await register(page, email, 'Cliente E2E')
  const cookie = (await page.context().cookies()).find(
    (item) => item.name === 'better-auth.session_token',
  )
  expect(cookie?.httpOnly).toBe(true)
  expect(cookie?.sameSite).toBe('Lax')
  const stored = await pool.query('SELECT "emailVerified" FROM "user" WHERE email = $1', [email])
  expect(stored.rows).toEqual([{ emailVerified: false }])
  await page.goto(`${base}/ingresar`)
  await expect(page).toHaveURL(`${base}/cuenta`)
  await page.goto(`${base}/cuenta/direcciones`)
  await addAddress(page, 'Casa E2E')
  await addAddress(page, 'Oficina E2E')
  await expect(page.getByText('Predeterminada', { exact: true })).toHaveCount(1)
  await expect(
    page
      .getByRole('region', { name: 'Dirección de Oficina E2E' })
      .getByText('Predeterminada', { exact: true }),
  ).toBeVisible()
  const home = page.getByRole('region', { name: 'Dirección de Casa E2E' })
  await home.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Ciudad').fill('San Lorenzo')
  const editRequestPromise = page.waitForRequest(
    (request) => request.method() === 'POST' && Boolean(request.headers()['next-action']),
  )
  await page.getByRole('button', { name: 'Guardar dirección' }).click()
  const editRequest = await editRequestPromise
  await expect(home.getByText('San Lorenzo, Central')).toBeVisible()

  // A second browser has an independent session and cannot read the first customer's data.
  const context = await browser.newContext()
  const second = await context.newPage()
  try {
    await register(second, otherEmail, 'Otro cliente E2E')
    await second.goto(`${base}/cuenta/direcciones`)
    await expect(second.getByText('Todavía no guardaste ninguna dirección.')).toBeVisible()
    const denied = await second.request.get(`${base}/api/addresses`)
    expect([401, 403]).toContain(denied.status())
    // Replay a real mutation with a different customer's cookie, bypassing the UI.
    const forged = await second.request.post(editRequest.url(), {
      headers: {
        'next-action': editRequest.headers()['next-action'],
        'content-type': editRequest.headers()['content-type'],
        origin: base,
      },
      data: editRequest.postDataBuffer()!,
    })
    expect(await forged.text()).toContain('La dirección no existe.')
    await second.goto(`${base}/catalogar`)
    await expect(second.getByRole('heading', { name: 'Mis direcciones' })).toHaveCount(0)
    await expect(second).toHaveURL(`${base}/admin/login`, { timeout: 20_000 })
  } finally {
    await context.close()
  }

  // Delete through the real action, and confirm it survives a full reload.
  await home.getByRole('button', { name: 'Eliminar', exact: true }).click()
  await page.getByRole('button', { name: 'Sí, eliminar', exact: true }).click()
  await expect(home).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Dirección de Oficina E2E' })).toBeVisible()
  await page.getByRole('button', { name: 'Menú de mi cuenta' }).click()
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await expect(page).toHaveURL(`${base}/ingresar`)
  await page.goto(`${base}/cuenta`)
  await expect(page).toHaveURL(`${base}/ingresar`)
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill('Incorrect-password!')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(
    page.getByRole('alert').filter({ hasText: 'Email o contraseña incorrectos' }),
  ).toBeVisible()
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page).toHaveURL(`${base}/cuenta`)
})

test('Payload admins retain CMS access without gaining a customer session', async ({ page }) => {
  test.setTimeout(120_000)
  const { getPayload } = await import('payload')
  const { default: config } = await import('../../src/payload.config')
  // Instancia propia: otros specs destruyen la instancia 'default' que getPayload deja en caché
  // dentro del mismo worker, y un pool cerrado cuelga payload.create hasta el timeout.
  const payload = await getPayload({ config, key: `customer-auth-e2e-${run}` })
  let adminId: number | undefined
  try {
    const adminEmail = `fase2-admin-${randomUUID()}@example.com`
    const admin = await payload.create({
      collection: 'users',
      data: { email: adminEmail, password },
    })
    adminId = admin.id
    const login = await page.request.post(`${base}/api/users/login`, {
      data: { email: adminEmail, password },
    })
    expect(login.ok()).toBe(true)
    const addresses = await page.request.get(`${base}/api/addresses`)
    expect(addresses.ok()).toBe(true)
    await page.goto(`${base}/catalogar`)
    await expect(page.getByRole('heading', { name: 'Cargar producto', exact: true })).toBeVisible()
    await page.goto(`${base}/admin/collections/addresses`)
    await expect(
      page.getByRole('heading', { name: 'Direcciones de clientes', exact: true }),
    ).toBeVisible({ timeout: 20_000 })
    expect(await (await page.request.get(`${base}/api/auth/get-session`)).json()).toBeNull()
    await page.goto(`${base}/cuenta`)
    await expect(page).toHaveURL(`${base}/ingresar`, { timeout: 20_000 })
  } finally {
    if (adminId) await payload.delete({ collection: 'users', id: adminId })
    await payload.destroy()
  }
})
