import 'dotenv/config'
import { randomUUID } from 'node:crypto'
import { Pool } from 'pg'
import { expect, test, type Page } from '@playwright/test'
import {
  fillRegistration,
  readEmailCode,
  resetAuthRateLimits,
  submitVerificationCode,
} from '../helpers/customerAuth'

const base = 'http://localhost:3000'
const run = randomUUID()
const email = `fase2-${run}@example.com`
const otherEmail = `fase2-other-${run}@example.com`
const mismatchEmail = `fase2-mismatch-${run}@example.com`
const codeEmail = `fase2-code-${run}@example.com`
const resetEmail = `fase2-reset-${run}@example.com`
const squatEmail = `fase2-squat-${run}@example.com`
const fixtureEmails = [email, otherEmail, mismatchEmail, codeEmail, resetEmail, squatEmail]
const password = `Test-${run}!`
const pool = new Pool({ connectionString: process.env.DATABASE_URL })

test.afterAll(async () => {
  // Only delete the fixtures generated by this run; sessions/accounts cascade.
  await pool.query(
    'DELETE FROM addresses WHERE customer_id IN (SELECT id FROM "user" WHERE email = ANY($1))',
    [fixtureEmails],
  )
  await pool.query('DELETE FROM "user" WHERE email = ANY($1)', [fixtureEmails])
  await pool.query('DELETE FROM verification WHERE identifier LIKE ANY($1)', [
    fixtureEmails.map((item) => `%${item}`),
  ])
  await pool.end()
})

async function register(page: Page, userEmail: string, name: string) {
  await resetAuthRateLimits()
  await page.goto(`${base}/registrarse`)
  await fillRegistration(page, { name, email: userEmail, password })
  await submitVerificationCode(page, userEmail)
  await expect(page).toHaveURL(`${base}/cuenta`)
  await expect(page.getByRole('button', { name: 'Menú de mi cuenta' })).toBeVisible()
}

async function addAddress(page: Page, name: string) {
  await page.getByRole('button', { name: 'Agregar dirección' }).click()
  await page.getByLabel('Destinatario').fill(name)
  await page.getByLabel('Teléfono').fill('0981 123456')
  await page.getByLabel('Departamento').selectOption('Central')
  await page.getByLabel('Ciudad').fill('Luque')
  await page.getByLabel('Dirección / referencia').fill('Dirección ficticia de prueba')
  await page.getByLabel('Usar como dirección predeterminada').check()
  await page.getByRole('button', { name: 'Guardar dirección' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
}

test('registration requires the password to be typed twice', async ({ page }) => {
  await pool.query('DELETE FROM rate_limit')
  await page.goto(`${base}/registrarse`)
  await page.getByLabel('Nombre completo').fill('Cliente Distinto')
  await page.getByLabel('Email', { exact: true }).fill(mismatchEmail)
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill(`${password}x`)
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await expect(page.locator('form').getByRole('alert')).toContainText(
    'Las contraseñas no coinciden',
  )
  await expect(page.getByLabel('Confirmar contraseña', { exact: true })).toHaveAttribute(
    'aria-invalid',
    'true',
  )
  await expect(page).toHaveURL(`${base}/registrarse`)
  const stored = await pool.query('SELECT 1 FROM "user" WHERE email = $1', [mismatchEmail])
  expect(stored.rows).toHaveLength(0)

  // Corrigiendo la confirmación el registro avanza a la verificación del email.
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click()
  await submitVerificationCode(page, mismatchEmail)
  await expect(page).toHaveURL(`${base}/cuenta`)
})

test('an account cannot sign in until its email is verified with the emailed code', async ({
  page,
}) => {
  test.setTimeout(120_000)
  await resetAuthRateLimits()
  await page.goto(`${base}/registrarse`)
  await fillRegistration(page, { name: 'Cliente Código', email: codeEmail, password })
  await expect(page).toHaveURL(/\/verificar-email/)
  // El email nunca viaja en la URL.
  expect(page.url()).not.toContain('example.com')
  const stored = await pool.query('SELECT "emailVerified" FROM "user" WHERE email = $1', [
    codeEmail,
  ])
  expect(stored.rows).toEqual([{ emailVerified: false }])
  // Sin verificar no hay sesión ni acceso al área privada.
  await page.goto(`${base}/cuenta`)
  await expect(page).toHaveURL(`${base}/ingresar`)

  // Ingresar con la contraseña correcta pero sin verificar lleva a pedir el código.
  await resetAuthRateLimits()
  await page.getByLabel('Email', { exact: true }).fill(codeEmail)
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page).toHaveURL(/\/verificar-email/)

  // Un código incorrecto se rechaza con un mensaje claro y no inicia sesión.
  const real = await readEmailCode(codeEmail)
  const wrong = real === '000000' ? '111111' : '000000'
  await page.getByLabel('Código de verificación').fill(wrong)
  await page.getByRole('button', { name: 'Verificar', exact: true }).click()
  await expect(page.locator('form').getByRole('alert')).toContainText('incorrecto')
  await expect(page).toHaveURL(/\/verificar-email/)

  // El código correcto verifica el email e inicia sesión.
  await page.getByLabel('Código de verificación').fill(real)
  await page.getByRole('button', { name: 'Verificar', exact: true }).click()
  await expect(page).toHaveURL(`${base}/cuenta`)
  const verified = await pool.query('SELECT "emailVerified" FROM "user" WHERE email = $1', [
    codeEmail,
  ])
  expect(verified.rows).toEqual([{ emailVerified: true }])
})

test('the real owner replaces an unverified account registered first with their email', async ({
  page,
}) => {
  test.setTimeout(120_000)
  const attackerPassword = `Atacante-${run}!`
  const ownerPassword = `Duenio-${run}!`
  await resetAuthRateLimits()
  // Alguien registra el email de otra persona y no puede verificarlo.
  const squat = await page.request.post(`${base}/api/auth/sign-up/email`, {
    headers: { origin: base },
    data: { email: squatEmail, password: attackerPassword, name: 'Atacante' },
  })
  expect(squat.ok()).toBe(true)

  // El verdadero dueño se registra con su propia contraseña y verifica el código.
  await page.goto(`${base}/registrarse`)
  await fillRegistration(page, { name: 'Dueño Real', email: squatEmail, password: ownerPassword })
  await submitVerificationCode(page, squatEmail)
  await expect(page).toHaveURL(`${base}/cuenta`)

  // Solo sirve la contraseña del dueño.
  await resetAuthRateLimits()
  const attacker = await page.request.post(`${base}/api/auth/sign-in/email`, {
    headers: { origin: base },
    data: { email: squatEmail, password: attackerPassword },
  })
  expect(attacker.status()).toBe(401)
  const owner = await page.request.post(`${base}/api/auth/sign-in/email`, {
    headers: { origin: base },
    data: { email: squatEmail, password: ownerPassword },
  })
  expect(owner.status()).toBe(200)
})

test('a customer can recover the password with an emailed code', async ({ page }) => {
  test.setTimeout(120_000)
  const newPassword = `Nueva-${run}!`
  await register(page, resetEmail, 'Cliente Recupera')
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await expect(page).toHaveURL(`${base}/ingresar`)

  await resetAuthRateLimits()
  await page.getByRole('link', { name: '¿Olvidaste tu contraseña?' }).click()
  await expect(page).toHaveURL(`${base}/olvide-contrasena`)
  await page.getByLabel('Email', { exact: true }).fill(resetEmail)
  await page.getByRole('button', { name: 'Enviar código', exact: true }).click()
  await expect(page).toHaveURL(`${base}/restablecer-contrasena`)

  const code = await readEmailCode(resetEmail, 'forget-password')
  await page.getByLabel('Código de verificación').fill(code)
  await page.getByLabel('Contraseña nueva', { exact: true }).fill(newPassword)
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill(`${newPassword}x`)
  await page.getByRole('button', { name: 'Cambiar contraseña', exact: true }).click()
  await expect(page.locator('form').getByRole('alert')).toContainText('no coinciden')

  await page.getByLabel('Confirmar contraseña', { exact: true }).fill(newPassword)
  await page.getByRole('button', { name: 'Cambiar contraseña', exact: true }).click()
  await expect(page).toHaveURL(`${base}/ingresar?restablecida=1`)
  await expect(page.getByText('Actualizamos tu contraseña')).toBeVisible()

  // La contraseña anterior deja de servir y la nueva inicia sesión.
  await resetAuthRateLimits()
  await page.getByLabel('Email', { exact: true }).fill(resetEmail)
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page.locator('form').getByRole('alert')).toContainText('incorrectos')
  await page.getByLabel('Contraseña', { exact: true }).fill(newPassword)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page).toHaveURL(`${base}/cuenta`)

  // Un código ya usado no sirve otra vez.
  await resetAuthRateLimits()
  const reuse = await page.request.post(`${base}/api/auth/email-otp/reset-password`, {
    headers: { origin: base },
    data: { email: resetEmail, otp: code, password: `Otra-${run}!` },
  })
  expect(reuse.status()).toBe(400)
})

test('customer lifecycle, address isolation, default switch and protected routes', async ({
  page,
  browser,
}) => {
  test.setTimeout(180_000)
  expect(await (await page.request.get(`${base}/api/auth/ok`)).json()).toEqual({ ok: true })
  await page.goto(`${base}/cuenta/direcciones`)
  await expect(page).toHaveURL(`${base}/ingresar`)
  await register(page, email, 'Cliente E2E')
  const cookie = (await page.context().cookies()).find(
    (item) => item.name === 'better-auth.session_token',
  )
  expect(cookie?.httpOnly).toBe(true)
  expect(cookie?.sameSite).toBe('Lax')
  const stored = await pool.query('SELECT "emailVerified" FROM "user" WHERE email = $1', [email])
  expect(stored.rows).toEqual([{ emailVerified: true }])
  await page.goto(`${base}/ingresar`)
  await expect(page).toHaveURL(`${base}/cuenta`)
  await page.goto(`${base}/cuenta/direcciones`)
  await addAddress(page, 'Casa E2E')
  await addAddress(page, 'Oficina E2E')
  await expect(page.getByText('Predeterminada', { exact: true })).toHaveCount(1)
  await expect(
    page
      .getByRole('region', { name: 'Dirección de Oficina E2E' })
      .getByText('Predeterminada', { exact: true }),
  ).toBeVisible()
  const home = page.getByRole('region', { name: 'Dirección de Casa E2E' })
  await home.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Ciudad').fill('San Lorenzo')
  const editRequestPromise = page.waitForRequest(
    (request) => request.method() === 'POST' && Boolean(request.headers()['next-action']),
  )
  await page.getByRole('button', { name: 'Guardar dirección' }).click()
  const editRequest = await editRequestPromise
  await expect(home.getByText('San Lorenzo, Central')).toBeVisible()

  // A second browser has an independent session and cannot read the first customer's data.
  const context = await browser.newContext()
  const second = await context.newPage()
  try {
    await register(second, otherEmail, 'Otro cliente E2E')
    await second.goto(`${base}/cuenta/direcciones`)
    await expect(second.getByText('Todavía no guardaste ninguna dirección.')).toBeVisible()
    const denied = await second.request.get(`${base}/api/addresses`)
    expect([401, 403]).toContain(denied.status())
    // Replay a real mutation with a different customer's cookie, bypassing the UI.
    const forged = await second.request.post(editRequest.url(), {
      headers: {
        'next-action': editRequest.headers()['next-action'],
        'content-type': editRequest.headers()['content-type'],
        origin: base,
      },
      data: editRequest.postDataBuffer()!,
    })
    expect(await forged.text()).toContain('La dirección no existe.')
    await second.goto(`${base}/catalogar`)
    await expect(second.getByRole('heading', { name: 'Mis direcciones' })).toHaveCount(0)
    await expect(second).toHaveURL(`${base}/admin/login`, { timeout: 20_000 })
  } finally {
    await context.close()
  }

  // Delete through the real action, and confirm it survives a full reload.
  await home.getByRole('button', { name: 'Eliminar', exact: true }).click()
  await page.getByRole('button', { name: 'Sí, eliminar', exact: true }).click()
  await expect(home).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Dirección de Oficina E2E' })).toBeVisible()
  await page.getByRole('button', { name: 'Menú de mi cuenta' }).click()
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await expect(page).toHaveURL(`${base}/ingresar`)
  await page.goto(`${base}/cuenta`)
  await expect(page).toHaveURL(`${base}/ingresar`)
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill('Incorrect-password!')
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(
    page.getByRole('alert').filter({ hasText: 'Email o contraseña incorrectos' }),
  ).toBeVisible()
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click()
  await expect(page).toHaveURL(`${base}/cuenta`)
})

test('Payload admins retain CMS access without gaining a customer session', async ({ page }) => {
  test.setTimeout(120_000)
  const { getPayload } = await import('payload')
  const { default: config } = await import('../../src/payload.config')
  // Instancia propia: otros specs destruyen la instancia 'default' que getPayload deja en caché
  // dentro del mismo worker, y un pool cerrado cuelga payload.create hasta el timeout.
  const payload = await getPayload({ config, key: `customer-auth-e2e-${run}` })
  let adminId: number | undefined
  try {
    const adminEmail = `fase2-admin-${randomUUID()}@example.com`
    const admin = await payload.create({
      collection: 'users',
      data: { email: adminEmail, password },
    })
    adminId = admin.id
    const login = await page.request.post(`${base}/api/users/login`, {
      data: { email: adminEmail, password },
    })
    expect(login.ok()).toBe(true)
    const addresses = await page.request.get(`${base}/api/addresses`)
    expect(addresses.ok()).toBe(true)
    await page.goto(`${base}/catalogar`)
    await expect(page.getByRole('heading', { name: 'Cargar producto', exact: true })).toBeVisible()
    await page.goto(`${base}/admin/collections/addresses`)
    await expect(
      page.getByRole('heading', { name: 'Direcciones de clientes', exact: true }),
    ).toBeVisible({ timeout: 20_000 })
    expect(await (await page.request.get(`${base}/api/auth/get-session`)).json()).toBeNull()
    await page.goto(`${base}/cuenta`)
    await expect(page).toHaveURL(`${base}/ingresar`, { timeout: 20_000 })
  } finally {
    if (adminId) await payload.delete({ collection: 'users', id: adminId })
    await payload.destroy()
  }
})
